config/routes.rb
BPEv075::Application.routes.draw do

  resources :deals

  resources :deal_stages
  match 'flat/add',:to=>"flats#add", :as=>"add_flat"
  match 'res_data/:id',:to=>"searchings#res_data"

  match 'surveyor',:to=>"pois#surveyor", :as=>"surveyor"
  match 'building/new',:to=>"buildings#new", :as=>"add_building"
  match 'search_results/:id', :to=>"searchings#results", :as=>"search_result"
  match 'property/(:building_id)/quick_form', :to => "buildings#quick_form", :as => "new_property"
  match 'flat_table/', :to => "flats#quick_index", :as => "quick_property_index"
  match 'building/:building_id/flat/:id/detailed_form/basic', :to => "buildings#detailed_form", :as => "edit_property_basic"
  match 'building/:building_id/flat/:id/detailed_form/location', :to => "buildings#building_location", :as => "edit_property_location"
  match 'building/:building_id/flat/:id/detailed_form/building_features', :to => "buildings#building_features", :as => "edit_property_building_features"
  match 'building/:building_id/flat/:id/detailed_form/flat_features', :to => "buildings#flat_features", :as => "edit_property_flat_features"
  match 'building/:building_id/flat/:id/detailed_form/photos', :to => "buildings#photos", :as => "edit_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/tag_photos', :to => "buildings#tag_photos", :as => "tag_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/moreinfo', :to => "buildings#moreinfo", :as => "edit_property_flat_moreinfo"
  match 'building/:building_id/flat/:id/detailed_form/terms', :to => "buildings#terms", :as => "edit_property_terms"
  match 'building/:id/:flat_id', :to => "buildings#show", :as => "show_building"
  match 'property/:id', :to => "flats#show", :as => "show_property"
  match 'network_map/:id', :to => "contacts#network_map", :as => "network_map"
  match "building/crop", :to =>  "buildings#crop"

  match 'property/notes/:building_id/:flat_id', :to => "flats#notes", :as => "notes"
  match 'flatasks/:id', :to=> "flats#flatasks", :as => "flatask"

  resources :searchings
  resources :interaction_entities
  resources :taskings
  resources :interactions
  resources :interaction_types
  resources :contacts
  resources :connections
  resources :buildings
  resources :flats
  resources :tasks
  resources :photos
  resources :building_services
  resources :pois
  resources :flat_contacts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  devise_for :users
  match "reschedule" => "taskings#reschedule"
  match "get_contact_list" => "buildings#get_contact_list"
  match "markup_as_cancle/:id"=>"taskings#markup_as_cancle"
  match "markup_as_complete/:id"=>"taskings#markup_as_complete"
  match "rename_photo/:photo_id" => "photos#rename_photo", :as => "rename_photo"
  match "delete_all_photos/:flat_id" => "photos#delete_all_photos", :as => "delete_all_photos"
  match "make_showcase_image/:flat_id/:photo_id" => "photos#make_showcase_image", :as => "make_showcase_image"
  match "update_photo_sequence" => "photos#update_photo_sequence", :as => "update_photo_sequence"
  match "save_photo_positions/:photo_id/:xpos/:ypos" => "photos#save_photo_positions", :as => "save_photo_positions"
  match "make_floor_plan/:flat_id/:photo_id" => "photos#make_floor_plan", :as => "make_floor_plan"
  match "/create_floor_plan"  => "photos#create_floor_plan" , :as => "create_floor_plan"
  match "dashboard", :to => "welcome#index", :as => "dashboard"
  match "/crop_floorplan", :to => "buildings#crop_floorplan", :as => "crop_floorplan"

  root :to => 'welcome#home'

end

app/models/flat.rb
class Flat < ActiveRecord::Base




  belongs_to :flatype
  belongs_to :furnstat
  belongs_to :building
  belongs_to :bhk_config
  belongs_to :direction

  has_many :flat_facilities, :dependent => :destroy
  has_many :facilities, :through => :flat_facilities
  has_many :flat_facility_features, :dependent => :destroy
  has_many :facility_features, :through => :flat_facility_features

  has_many :available_froms, :dependent => :destroy
  has_many :flat_notes, :dependent => :destroy
  has_many :balconies, :dependent => :destroy
  has_many :bathrooms, :dependent => :destroy
  has_many :brokerages, :dependent => :destroy
  has_many :deals, :dependent => :destroy
  has_many :expected_rents, :dependent => :destroy
  has_many :flat_ciphers, :dependent => :destroy
  has_many :flat_contacts, :dependent => :destroy
  has_many :contacts, :through => :flat_contacts
  has_many :flat_restrictions, :dependent => :destroy
  has_many :restrictions, :through => :flat_restrictions
  has_many :parkings, :dependent => :destroy
  has_many :rental_terms, :dependent => :destroy
  has_many :showings, :dependent => :destroy
  has_many :photos, :dependent => :destroy

  accepts_nested_attributes_for :flat_notes, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :rental_terms
  accepts_nested_attributes_for :expected_rents, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :available_froms, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :flat_contacts, :reject_if => proc { |attrs| reject = %w(flat_id contact_id labelling_id).all? { |a| attrs[a].blank? } }, :allow_destroy => true
  accepts_nested_attributes_for :contacts, :reject_if => proc { |attrs| reject = %w(name).all? { |a| attrs[a].blank? } }, :allow_destroy => true
  accepts_nested_attributes_for :photos, :reject_if => proc { |attrs| reject = %w(image).all? { |a| attrs[a].blank? } }, :allow_destroy => true

  accepts_nested_attributes_for :flat_facilities, :reject_if => lambda { |a| a[:facility_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :flat_facility_features, :reject_if => lambda { |a| a[:facility_feature_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :bathrooms, :reject_if => lambda { |a| a[:bathroom_type_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :balconies, :reject_if => lambda { |a| a[:balcony_type_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :parkings, :reject_if => lambda { |a| a[:parking_type_id].blank? }, :allow_destroy => true

  validates_presence_of :name, :message => "Flat name not entered"
  validates_presence_of :bhk_config_id, :message => "Flat Configuration not entered"

  has_attached_file :floorplan,
                    :styles => {
                        :original => {
                            :geometry => "640x600>"
                        },
                        :lightbox => {
                            :geometry => "640x600>"
                        },
                        :thumb => {
                            :geometry => "300x300!"
                        }
                    }, :processors => [:cropper]

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_floorplan, :if =>:cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def floorplan_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(floorplan.path(style))
  end



  def reprocess_floorplan
    floorplan.reprocess!
  end

  #before_create :create_flat_key
  after_create :create_basics

  def create_flat_key
    self.flat_key= "BPE" +Building.find(self.building_id).name[3]+ (Flat.last.blank? ? '10000' : "#{Flat.last.flat_key[-5, 5].to_i+1}")
  end

  def create_basics
    BathroomType.all.each do |type|
      Bathroom.create!(:flat_id => self.id, :bathroom_type_id => type.id, :value=>0)
    end
    BalconyType.all.each do |type|
      Balcony.create!(:flat_id => self.id, :balcony_type_id => type.id, :value=>0)
    end
    ParkingType.all.each do |type|
      Parking.create!(:flat_id => self.id, :parking_type_id => type.id, :value=>0)
    end
    PropertyMaster.create(:flat_key=>self.flat_key,
                          :flat_name=>self.name,
                          :building_name=>self.building.name,
                          :locality=>self.building.primary_locality.name+"-"+self.building.primary_locality.area.name+","+self.building.localities.map { |l| l.name+"-"+l.area.name }.join(","),
                          :area=>self.area,
                          :bhk_config=>self.bhk_config.name,
                          :furn_status=>self.furnstat.name,
                          :rent=>self.expected_rents.map { |k| k.name }.join(","),
                          :related_people=>self.contacts.map { |c| c.name + (c.phones.first.blank? ? "" : "-" + c.phones.first.name) }.join(","),
                          :available_from=>self.available_froms.map { |af| af.name.blank? ? " " : af.name.strftime(" %b %y") }.join(","),
                          :floor=>self.floor,
                          :bathroom=>self.bathrooms.sum(:value),
                          :parking=>self.parkings.sum(:value),
                          :flat_facilities=>self.facilities.map { |f| f.name }.join(","),
                          :building_facilities=>self.building.facilities.map { |f| f.name }.join(","),
                          :restriction=>self.restrictions.map { |r| r.name }.join(","),
                          :flat_quality=>self.overall_quality
                          )
  end

  def furnstat
    if super.nil?
      e=ErrorObject.get_error_object(:name,"-")
      e
    else
      super
    end
  end

  def overall_quality
    @building_quality=Quality.find(self.building.building_quality_id)
    @approach_quality=Quality.find(self.building.approach_quality_id)
    @interiors_quality=Quality.find(self.interiors_quality_id)
    @view_quality=Quality.find(self.view_quality_id)

    @locality_quality=self.building.main_locality.quality
    @overall_quality=((@building_quality.value*2+@interiors_quality.value*2+@locality_quality.value*2+@approach_quality.value+@view_quality.value).to_f/8.0).round(0)
    Quality.find_by_value(@overall_quality).name
    end

  def overall_quality_score
    @building_quality=Quality.find(self.building.building_quality_id)
    @approach_quality=Quality.find(self.building.approach_quality_id)
    @interiors_quality=Quality.find(self.interiors_quality_id)
    @view_quality=Quality.find(self.view_quality_id)

    @locality_quality=self.building.main_locality.quality
    (((@building_quality.value*2+@interiors_quality.value*2+@locality_quality.value*2+@approach_quality.value+@view_quality.value).to_f/8.0)*10).round(0)
  end


end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:show, :index]


  # GET /flats
  # GET /flats.json
  def index
    if current_user
      @flats = Flat.all
    else
      @flats = Flat.where('displayed=? and approved=?', true, true).all
    end

    @facilities=Facility.where("is_building=?", true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flats }
    end
  end

  def quick_index
    if current_user
      @flats = Flat.all
    else
      @flats = Flat.where('displayed=? and approved=?', true, true).all
    end

    @facilities=Facility.where("is_building=?", true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flats }
    end
  end

  # GET /flats/1
  # GET /flats/1.json
  def show

    if current_user
      @flat = Flat.find(params[:id])
    elsif Flat.find(params[:id]).displayed and Flat.find(params[:id]).approved
      @flats = Flat.find(params[:id])
    else
      @flat=nil
    end

    @building = @flat.building
    @building_quality=Quality.find(@building.building_quality_id)
    @approach_quality=Quality.find(@building.approach_quality_id)
    @interiors_quality=Quality.find(@flat.interiors_quality_id)
    @view_quality=Quality.find(@flat.view_quality_id)

    @locality_quality=@building.main_locality.quality
    @overall_quality_value = ((@building_quality.value*2+@interiors_quality.value*2+@locality_quality.value*2+@approach_quality.value+@view_quality.value).to_f/8.0).round(0)
    @overall_quality_name = Quality.find_by_value(@overall_quality_value).name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flat }
    end
  end

  # GET /flats/new
  # GET /flats/new.json
  def new
    @flat = Flat.new
    @bhk_configs = BhkConfig.all
    @flatypes= Flatype.all
    @furnstat= Furnstat.all
    @directions= Direction.all
    @qualities= Quality.all

    @intq=@flat.interiors_qualities.build
    @vq=@flat.view_qualities.build

    @facilities=Facility.where("is_building=?", true)

    @features=Hash.new
    @facilities.each do |facility|
      @features[facility.name]=facility.facility_features
    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flat }
    end
  end

  # GET /flats/1/edit
  def edit
    @flat = Flat.find(params[:id])
    @building = Building.find(params[:building_id])

    @bhk_configs = BhkConfig.all
    @flatypes= Flatype.all
    @furnstats= Furnstat.all
    @directions= Direction.all
    @qualities= Quality.all

    @intq=@flat.interiors_qualities.build
    @vq=@flat.view_qualities.build

    @facilities=Facility.where("is_building=?", false)

    @features=Hash.new
    @facilities.each do |facility|
      @features[facility.name]=facility.facility_features
    end


  end

  # POST /flats
  # POST /flats.json
  def create
    #render :text=>params
    #return
    @flat = Flat.new(params[:flat])

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render json: @flat, status: :created, location: @flat }
      else
        format.html { render action: "new" }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flats/1
  # PUT /flats/1.json
  def update
    @flat = Flat.find(params[:id])
    @flat.save
    respond_to do |format|
      if @flat.update_attributes(params[:flat])
        format.html { redirect_to edit_property_flat_photos_path(@flat.building, @flat), :notice => 'Photos were successfully uploaded.' }
      else
        format.html { render action: "edit" }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url }
      format.json { head :no_content }
    end
  end

  def notes
    @flat = Flat.find(params[:flat_id])
    @building = @flat.building
    @building_quality=Quality.find(@building.building_quality_id)
    @approach_quality=Quality.find(@building.approach_quality_id)
    @interiors_quality=Quality.find(@flat.interiors_quality_id)
    @view_quality=Quality.find(@flat.view_quality_id)
    @flat.flat_notes.build
    unless @flat.available_froms
      @flat.available_froms.build
    end
    unless @flat.expected_rents
      @flat.expected_rents.build
    end
    @locality_quality=@building.main_locality.quality
    @overall_quality_value = ((@building_quality.value*2+@interiors_quality.value*2+@locality_quality.value*2+@approach_quality.value+@view_quality.value).to_f/8.0).round(0)
    @overall_quality_name = Quality.find_by_value(@overall_quality_value).name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flat }
    end
  end

  def flatasks

    @flat_page=true

    @flat = Flat.find(params[:id])
    @building = @flat.building
    @building_quality=Quality.find(@building.building_quality_id)
    @approach_quality=Quality.find(@building.approach_quality_id)
    @interiors_quality=Quality.find(@flat.interiors_quality_id)
    @view_quality=Quality.find(@flat.view_quality_id)
    @locality_quality=@building.main_locality.quality
    @overall_quality_value = ((@building_quality.value*2+@interiors_quality.value*2+@locality_quality.value*2+@approach_quality.value+@view_quality.value).to_f/8.0).round(0)
    @overall_quality_name = Quality.find_by_value(@overall_quality_value).name

    @involved_interactions = InteractionFlat.where('flat_id=?', @flat.id).all.map { |i| i.interaction }
    @tasks = @involved_interactions.map { |i| i.taskings.first }.compact.uniq

    @interactions=@involved_interactions
    @interaction=Interaction.new
    @interaction.taskings.build

  end

  def add
    @flat = Flat.new
=begin
    @bhk_configs = BhkConfig.all
    @flatypes= Flatype.all
    @furnstat= Furnstat.all
    @directions= Direction.all
=end
    #@qualities= Quality.all

    #@intq=@flat.interiors_qualities.build
    #@vq=@flat.view_qualities.build

    @facilities=Facility.where("is_building=?", true)

    @features=Hash.new
    @facilities.each do |facility|
      @features[facility.name]=facility.facility_features
    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flat }
    end
  end

end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_property_index.html.erb
<%#= javascript_include_tag "exclusions/dhtmlxcommon" %>
<%#= javascript_include_tag "exclusions/dhtmlxgrid" %>
<%#= javascript_include_tag "exclusions/dhtmlxgrid_filter" %>
<%#= javascript_include_tag "exclusions/dhtmlxgrid_srnd" %>
<%#= javascript_include_tag "exclusions/dhtmlxgrid_start" %>
<%#= javascript_include_tag "exclusions/dhtmlxgridcell" %>
<%#= javascript_include_tag "exclusions/dhtmlXGrid_srnd" %>

<%= javascript_include_tag "exclusions/jquery.dataTables" %>
<%= stylesheet_link_tag "exclusions/jquery.dataTables" %>

<%= javascript_include_tag "exclusions/ColVis" %>
<%= stylesheet_link_tag "exclusions/ColVis" %>

<div class="content" style="margin-top: 25px;">
  <div class="row">
    <table>
      <tr>
        <td><h1 style="margin-left: 20px; margin-right: 40px;">Property Index</h1></td>
        <td><%= link_to "Basic View", quick_property_index_path, :class=>"btn btn-info btn-large" %></td>
        <td><%= link_to "Expanded View", flats_path, :class=>"btn btn-large btn-disabled" %></td>
      </tr>
    </table>
  </div>
</div>
<br>

<div class="content">
  <!--<table id="dhtmlxtable">-->
  <table id="datatable">
    <thead>
    <tr>
      <td>Flat-Key</td>
      <td>Flat Name</td>
      <td>Building Name</td>
      <td>Locality</td>
      <td>Area</td>
      <td>BHK Config</td>
      <td>Furn Status</td>
      <td>Rent</td>
      <td>Related People</td>
      <td>Available from</td>
      <td>Floor</td>
      <td>Bathroom</td>
      <td>Parking Slots</td>
      <td>Flat Facilities</td>
      <td>Building Facilities</td>
      <td>Restrictions</td>
      <td>Flat Quality</td>
      <td>Last Updated</td>
    </tr>
    </thead>
    <tbody>
    <% @flats.each do |flat| %>
        <tr>
          <td id=<%= flat.id+0 %>><%= link_to flat.flat_key, "property/#{flat.id}", :target => "_blank" %></td>
          <td <%= flat.id+1 %>><%= flat.name %></td>
          <td <%= flat.id+2 %>><%= flat.building.name %></td>
          <td <%= flat.id+3 %>><%= flat.building.primary_locality.name+"-"+flat.building.primary_locality.area.name+","+flat.building.localities.map { |l| l.name+"-"+l.area.name }.join(",") %></td>
          <td <%= flat.id+4 %>><%= flat.area %></td>
          <td <%= flat.id+5 %>><%= flat.bhk_config.name.split(" ")[0] %></td>
          <td <%= flat.id+6 %>><%= flat.furnstat.name %></td>
          <td <%= flat.id+7 %>><%= flat.expected_rents.map { |k| k.name }.join(",") %></td>
          <td <%= flat.id+8 %>><%= flat.contacts.map { |c| c.name + (c.phones.first.blank? ? "" : "-" + c.phones.first.name) }.join(",") %></td>
          <td <%= flat.id+9 %>><%= flat.available_froms.map { |af| af.name.blank? ? " " : af.name.strftime(" %b %y") }.join(",") %></td>
          <td <%= flat.id+10 %>><%= flat.floor %></td>
          <td <%= flat.id+11 %>><%= flat.bathrooms.sum(:value) %></td>
          <td <%= flat.id+12 %>><%= flat.parkings.sum(:value) %></td>
          <td <%= flat.id+13 %>><%= flat.facilities.map { |f| f.name }.join(",") %></td>
          <td <%= flat.id+14 %>><%= flat.building.facilities.map { |f| f.name }.join(",") %></td>
          <td <%= flat.id+15 %>><%= flat.restrictions.map { |r| r.name }.join(",") %></td>
          <td <%= flat.id+16 %>><%= flat.overall_quality %></td>
          <td <%= flat.id+17 %>><%= flat.updated_at.strftime(" %e %b %y") %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">

    $(document).ready(function() {
        $('#datatable').dataTable( {
            "bPaginate": true,
            "sPaginationType":"full_numbers",
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "oSearch": {"sSearch": ""},
            "sDom": 'C<"clear">lfrtip',
            "bAutoWidth": false } );
    } );

</script>

app/views/flats/_top_menu.html.erb
<%= content_for :head do %>

    <%= javascript_include_tag "exclusions/jquery.lightbox-0.5.min" %>
    <%= stylesheet_link_tag "exclusions/jquery.lightbox-0.5" %>
    <script type="text/javascript">
        $(function () {
            $('div.amenu a').popover({
                placement:'bottom',
                html:true
            });

            $('a.lightbox').lightBox(); // Select all links with lightbox class
        })
    </script>

    <style type="text/css">
        .btn-menu {
            width: 50px;
            margin-bottom: 5px;
        }
    </style>

<% end %>



<!-- Header Panel -->

<div class="content" style="margin-top: 40px;padding-top: 10px;padding-bottom: 0">
  <div class="row-fluid">
    <div class="span4" style="padding-top: 5px;padding-bottom: 5px;">
      Property Id: <strong><%= @flat.flat_key %></strong> |
      <small><%= link_to "Edit", edit_property_basic_path(@flat.building, @flat) %></small>
      <br>
      <%= @flat.building.main_locality.name %>, <%= @flat.building.main_locality.area.name %>
      , <%= @flat.building.main_locality.area.city.name %>
      <h2 style="position:relative;">
        <%= @flat.bhk_config.name %> in <%= @flat.building.name %>
        <br>
        <small>
          <div style="margin-top: -10px;">
            <%= @flat.furnstat.name unless @flat.furnstat.nil? %> |
            Rs <%= @flat.expected_rents.first.name unless @flat.expected_rents.first.nil? %> |
            <% unless @flat.available_froms.first.nil? %>
                <% unless @flat.available_froms.first.name.blank? %>
                    <%= @flat.available_froms.first.name.strftime('%b %Y') %>
                <% end %>
            <% end %>
          </div>
        </small>
      </h2>
    </div>
    <div class="span3 amenu" style="margin-top: 10px;">
      <%= link_to "Flat", show_property_path(@flat), :class => "btn btn-inverse btn-large btn-menu" %>
      <%= link_to "Building", show_building_path(@flat.building, @flat), :class => "btn btn-inverse btn-large btn-menu" %>
      <br>
      <%= link_to "Notes", notes_path(@flat.building, @flat), :class => "btn btn-inverse btn-large btn-menu" %>
      <%= link_to "Tasks", flatask_path(@flat), :class => "btn btn-inverse btn-large btn-menu" %>
    </div>
    <div class="span5 pull-right" style="padding-top: 5px;padding-bottom: 5px;">
      <div class="span2 pull-right">
        <div class="row-fluid">
          <div>
            <div class="row-fluid"><h4>Approach Quality</h4></div>
            <div class="row-fluid">
              <div class="span6">
                <%= @approach_quality.name %>
              </div>
              <div class="span6">
                <% @approach_quality.value.times do %>
                    <%= image_tag "rating-on.png" %>
                <% end %>
                <% (3-@approach_quality.value).times do %>
                    <%= image_tag "rating-off.png" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row-fluid" style="margin-top: 10px;">
          <div>
            <div class="row-fluid"><h4>View Quality</h4></div>
            <div class="row-fluid">
              <div class="span6">
                <%= @view_quality.name %>
              </div>
              <div class="span6">
                <% @view_quality.value.times do %>
                    <%= image_tag "rating-on.png" %>
                <% end %>
                <% (3-@view_quality.value).times do %>
                    <%= image_tag "rating-off.png" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="span2 pull-right">
        <div class="row-fluid">
          <div>
            <div class="row-fluid"><h4>Building Quality</h4></div>
            <div class="row-fluid">
              <div class="span6">
                <%= @building_quality.name %>
              </div>
              <div class="span6">
                <% @building_quality.value.times do %>
                    <%= image_tag "rating-on.png" %>
                <% end %>
                <% (3-@building_quality.value).times do %>
                    <%= image_tag "rating-off.png" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row-fluid" style="margin-top: 10px;">
          <div>
            <div class="row-fluid"><h4>Interiors Quality</h4></div>
            <div class="row-fluid">
              <div class="span6">
                <%= @interiors_quality.name %>
              </div>
              <div class="span6">
                <% @interiors_quality.value.times do %>
                    <%= image_tag "rating-on.png" %>
                <% end %>
                <% (3-@interiors_quality.value).times do %>
                    <%= image_tag "rating-off.png" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="span2 pull-right">
        <div class="row-fluid blocky" style="margin-top: -6px;margin-left: -7px;">
          <div>
            <div class="row-fluid"><h4>Overall Quality</h4></div>
            <div class="row-fluid">
              <div class="span6">
                <%= @overall_quality_name %>
              </div>
              <div class="span6">
                <% @overall_quality_value.times do %>
                    <%= image_tag "rating-on.png" %>
                <% end %>
                <% (3-@overall_quality_value).times do %>
                    <%= image_tag "rating-off.png" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row-fluid" style="margin-top: 5px;">
          <div>
            <div class="row-fluid"><h4>Locality Quality</h4></div>
            <div class="row-fluid">
              <div class="span6">
                <%= @locality_quality.name %>
              </div>
              <div class="span6">
                <% @locality_quality.value.times do %>
                    <%= image_tag "rating-on.png" %>
                <% end %>
                <% (3-@locality_quality.value).times do %>
                    <%= image_tag "rating-off.png" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
<%= render "property_index" %>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>