config/routes.rb
BPEv075::Application.routes.draw do

  resources :deals

  resources :deal_stages
  match 'flat/add',:to=>"flats#add", :as=>"add_flat"
  match 'res_data/:id',:to=>"searchings#res_data"

  match 'surveyor',:to=>"pois#surveyor", :as=>"surveyor"
  match 'building/new',:to=>"buildings#new", :as=>"add_building"
  match 'search_results/:id', :to=>"searchings#results", :as=>"search_result"
  match 'property/(:building_id)/quick_form', :to => "buildings#quick_form", :as => "new_property"
  match 'flat_table/', :to => "flats#quick_index", :as => "quick_property_index"
  match 'building/:building_id/flat/:id/detailed_form/basic', :to => "buildings#detailed_form", :as => "edit_property_basic"
  match 'building/:building_id/flat/:id/detailed_form/location', :to => "buildings#building_location", :as => "edit_property_location"
  match 'building/:building_id/flat/:id/detailed_form/building_features', :to => "buildings#building_features", :as => "edit_property_building_features"
  match 'building/:building_id/flat/:id/detailed_form/flat_features', :to => "buildings#flat_features", :as => "edit_property_flat_features"
  match 'building/:building_id/flat/:id/detailed_form/photos', :to => "buildings#photos", :as => "edit_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/tag_photos', :to => "buildings#tag_photos", :as => "tag_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/moreinfo', :to => "buildings#moreinfo", :as => "edit_property_flat_moreinfo"
  match 'building/:building_id/flat/:id/detailed_form/terms', :to => "buildings#terms", :as => "edit_property_terms"
  match 'building/:id/:flat_id', :to => "buildings#show", :as => "show_building"
  match 'property/:id', :to => "flats#show", :as => "show_property"
  match 'network_map/:id', :to => "contacts#network_map", :as => "network_map"
  match "building/crop", :to =>  "buildings#crop"

  match 'property/notes/:building_id/:flat_id', :to => "flats#notes", :as => "notes"
  match 'flatasks/:id', :to=> "flats#flatasks", :as => "flatask"

  resources :searchings
  resources :interaction_entities
  resources :taskings
  resources :interactions
  resources :interaction_types
  resources :contacts
  resources :connections
  resources :buildings
  resources :flats
  resources :tasks
  resources :photos
  resources :building_services
  resources :pois
  resources :flat_contacts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  devise_for :users
  match "reschedule" => "taskings#reschedule"
  match "get_contact_list" => "buildings#get_contact_list"
  match "markup_as_cancle/:id"=>"taskings#markup_as_cancle"
  match "markup_as_complete/:id"=>"taskings#markup_as_complete"
  match "rename_photo/:photo_id" => "photos#rename_photo", :as => "rename_photo"
  match "delete_all_photos/:flat_id" => "photos#delete_all_photos", :as => "delete_all_photos"
  match "make_showcase_image/:flat_id/:photo_id" => "photos#make_showcase_image", :as => "make_showcase_image"
  match "update_photo_sequence" => "photos#update_photo_sequence", :as => "update_photo_sequence"
  match "save_photo_positions/:photo_id/:xpos/:ypos" => "photos#save_photo_positions", :as => "save_photo_positions"
  match "make_floor_plan/:flat_id/:photo_id" => "photos#make_floor_plan", :as => "make_floor_plan"
  match "/create_floor_plan"  => "photos#create_floor_plan" , :as => "create_floor_plan"
  match "dashboard", :to => "welcome#index", :as => "dashboard"
  match "/crop_floorplan", :to => "buildings#crop_floorplan", :as => "crop_floorplan"

  root :to => 'welcome#home'

end

app/models/tasking.rb
class Tasking < ActiveRecord::Base
  belongs_to :interaction



end

app/controllers/taskings_controller.rb
class TaskingsController < ApplicationController
  # GET /taskings
  # GET /taskings.json
  def index
    @taskings = Tasking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taskings }
    end
  end

  # GET /taskings/1
  # GET /taskings/1.json
  def show
    @tasking = Tasking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tasking }
    end
  end

  # GET /taskings/new
  # GET /taskings/new.json
  def new
    @tasking = Tasking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tasking }
    end
  end

  # GET /taskings/1/edit
  def edit
    @tasking = Tasking.find(params[:id])
  end

  # POST /taskings
  # POST /taskings.json
  def create
    @tasking = Tasking.new(params[:tasking])

    respond_to do |format|
      if @tasking.save
        format.html { redirect_to @tasking, notice: 'Tasking was successfully created.' }
        format.json { render json: @tasking, status: :created, location: @tasking }
      else
        format.html { render action: "new" }
        format.json { render json: @tasking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taskings/1
  # PUT /taskings/1.json
  def update
    @tasking = Tasking.find(params[:id])

    respond_to do |format|
      if @tasking.update_attributes(params[:tasking])
        format.html { redirect_to @tasking, notice: 'Tasking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tasking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taskings/1
  # DELETE /taskings/1.json
  def destroy
    @tasking = Tasking.find(params[:id])
    @tasking.destroy

    respond_to do |format|
      format.html { redirect_to taskings_url }
      format.json { head :no_content }
    end
  end

  def markup_as_complete
    @tasking = Tasking.find(params[:id])
    @interaction=Interaction.find(@tasking.interaction_id)
    @interaction.name=@interaction.name.gsub("Completed:","")
    @interaction.name=@interaction.name.gsub("Cancled:","")
    @interaction.name="Completed:"+@interaction.name
    @interaction.save
    @tasking.save
    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.json { head :no_content }
    end
  end

  def markup_as_cancle
    @tasking = Tasking.find(params[:id])
    @interaction=Interaction.find(@tasking.interaction_id)
    @interaction.name=@interaction.name.gsub("Completed:","")
    @interaction.name=@interaction.name.gsub("Cancled:","")
    @interaction.name="Cancled:"+@interaction.name
    @interaction.save
    @tasking.save
    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.json { head :no_content }
    end
  end

  def reschedule
    @tasking = Tasking.find(params[:id])
    @tasking.due_date=params[:due_date]
    @tasking.save
    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.json { head :no_content }
    end
  end
end

app/views/taskings/_form.html.erb
<%= form_for(@tasking) do |f| %>
  <% if @tasking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasking.errors.count, "error") %> prohibited this tasking from being saved:</h2>

      <ul>
      <% @tasking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interaction_id %><br />
    <%= f.number_field :interaction_id %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %><br />
    <%= f.number_field :assigned_to %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taskings/edit.html.erb
<h1>Editing tasking</h1>

<%= render 'form' %>

<%= link_to 'Show', @tasking %> |
<%= link_to 'Back', taskings_path %>

app/views/taskings/index.html.erb
<h1>Listing taskings</h1>

<table>
  <tr>
    <th>Interaction</th>
    <th>Due date</th>
    <th>Assigned to</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taskings.each do |tasking| %>
  <tr>
    <td><%= tasking.interaction_id %></td>
    <td><%= tasking.due_date %></td>
    <td><%= tasking.assigned_to %></td>
    <td><%= tasking.active %></td>
    <td><%= link_to 'Show', tasking %></td>
    <td><%= link_to 'Edit', edit_tasking_path(tasking) %></td>
    <td><%= link_to 'Destroy', tasking, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tasking', new_tasking_path %>

app/views/taskings/new.html.erb
<h1>New tasking</h1>

<%= render 'form' %>

<%= link_to 'Back', taskings_path %>

app/views/taskings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Interaction:</b>
  <%= @tasking.interaction_id %>
</p>

<p>
  <b>Due date:</b>
  <%= @tasking.due_date %>
</p>

<p>
  <b>Assigned to:</b>
  <%= @tasking.assigned_to %>
</p>

<p>
  <b>Active:</b>
  <%= @tasking.active %>
</p>


<%= link_to 'Edit', edit_tasking_path(@tasking) %> |
<%= link_to 'Back', taskings_path %>