config/routes.rb
BPEv075::Application.routes.draw do

  resources :deals

  resources :deal_stages
  match 'flat/add',:to=>"flats#add", :as=>"add_flat"
  match 'res_data/:id',:to=>"searchings#res_data"

  match 'surveyor',:to=>"pois#surveyor", :as=>"surveyor"
  match 'building/new',:to=>"buildings#new", :as=>"add_building"
  match 'search_results/:id', :to=>"searchings#results", :as=>"search_result"
  match 'property/(:building_id)/quick_form', :to => "buildings#quick_form", :as => "new_property"
  match 'flat_table/', :to => "flats#quick_index", :as => "quick_property_index"
  match 'building/:building_id/flat/:id/detailed_form/basic', :to => "buildings#detailed_form", :as => "edit_property_basic"
  match 'building/:building_id/flat/:id/detailed_form/location', :to => "buildings#building_location", :as => "edit_property_location"
  match 'building/:building_id/flat/:id/detailed_form/building_features', :to => "buildings#building_features", :as => "edit_property_building_features"
  match 'building/:building_id/flat/:id/detailed_form/flat_features', :to => "buildings#flat_features", :as => "edit_property_flat_features"
  match 'building/:building_id/flat/:id/detailed_form/photos', :to => "buildings#photos", :as => "edit_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/tag_photos', :to => "buildings#tag_photos", :as => "tag_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/moreinfo', :to => "buildings#moreinfo", :as => "edit_property_flat_moreinfo"
  match 'building/:building_id/flat/:id/detailed_form/terms', :to => "buildings#terms", :as => "edit_property_terms"
  match 'building/:id/:flat_id', :to => "buildings#show", :as => "show_building"
  match 'property/:id', :to => "flats#show", :as => "show_property"
  match 'network_map/:id', :to => "contacts#network_map", :as => "network_map"
  match "building/crop", :to =>  "buildings#crop"

  match 'property/notes/:building_id/:flat_id', :to => "flats#notes", :as => "notes"
  match 'flatasks/:id', :to=> "flats#flatasks", :as => "flatask"

  resources :searchings
  resources :interaction_entities
  resources :taskings
  resources :interactions
  resources :interaction_types
  resources :contacts
  resources :connections
  resources :buildings
  resources :flats
  resources :tasks
  resources :photos
  resources :building_services
  resources :pois
  resources :flat_contacts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  devise_for :users
  match "reschedule" => "taskings#reschedule"
  match "get_contact_list" => "buildings#get_contact_list"
  match "markup_as_cancle/:id"=>"taskings#markup_as_cancle"
  match "markup_as_complete/:id"=>"taskings#markup_as_complete"
  match "rename_photo/:photo_id" => "photos#rename_photo", :as => "rename_photo"
  match "delete_all_photos/:flat_id" => "photos#delete_all_photos", :as => "delete_all_photos"
  match "make_showcase_image/:flat_id/:photo_id" => "photos#make_showcase_image", :as => "make_showcase_image"
  match "update_photo_sequence" => "photos#update_photo_sequence", :as => "update_photo_sequence"
  match "save_photo_positions/:photo_id/:xpos/:ypos" => "photos#save_photo_positions", :as => "save_photo_positions"
  match "make_floor_plan/:flat_id/:photo_id" => "photos#make_floor_plan", :as => "make_floor_plan"
  match "/create_floor_plan"  => "photos#create_floor_plan" , :as => "create_floor_plan"
  match "dashboard", :to => "welcome#index", :as => "dashboard"
  match "/crop_floorplan", :to => "buildings#crop_floorplan", :as => "crop_floorplan"

  root :to => 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_filter :authenticate_user!, :only=>:home

  def home
    @searching=Searching.new

    @searching.searching_bhk_configs.build
    @searching.searching_areas.build
    @searching.searching_facilities.build

    @bhk_configs=BhkConfig.all
    @areas=Area.all
    @facilities=Facility.all

    @budget_options=[[20000,20000],[25000,25000],[28000,28000],[30000,30000],[35000,35000],[40000,40000],[42000,42000],[45000,45000],[50000,50000]]

  end

  def index
    @assigned_tasks = Tasking.where('assigned_to=?',current_user.contact_id).all
    @involved_interactions = InteractionContact.where('contact_id=?',current_user.contact.id).all.map{|i| i.interaction}
    @involved_tasks = @involved_interactions.map{|i| if i.taskings.count>0 then i.taskings.first end}.compact
    if current_user.admin
      @tasks=Tasking.all
    else
      @tasks=(@assigned_tasks+@involved_tasks).uniq ||=[]
    end

    @interactions=Interaction.order("interaction_date DESC")
    @interaction=Interaction.new
    @interaction.taskings.build
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<style type="text/css">

    html {
        /*background: white;*/
    }

    body {
        background: rgb(254, 252, 234); /* Old browsers */
        background: -moz-radial-gradient(center, ellipse cover, rgba(254, 252, 234, 1) 0%, rgba(249, 228, 149, 1) 48%); /* FF3.6+ */
        background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%, rgba(254, 252, 234, 1)), color-stop(48%, rgba(249, 228, 149, 1))); /* Chrome,Safari4+ */
        background: -webkit-radial-gradient(center, ellipse cover, rgba(254, 252, 234, 1) 0%, rgba(249, 228, 149, 1) 48%); /* Chrome10+,Safari5.1+ */
        background: -o-radial-gradient(center, ellipse cover, rgba(254, 252, 234, 1) 0%, rgba(249, 228, 149, 1) 48%); /* Opera 12+ */
        background: -ms-radial-gradient(center, ellipse cover, rgba(254, 252, 234, 1) 0%, rgba(249, 228, 149, 1) 48%); /* IE10+ */
        background: radial-gradient(ellipse at center, rgba(254, 252, 234, 1) 0%, rgba(249, 228, 149, 1) 48%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = '#fefcea', endColorstr = '#f9e495', GradientType = 1); /* IE6-9 fallback on horizontal gradient */

        height: 420px;

        /*margin-top: 240px;*/
    }

    #site_logo {
        width: 300px;
        vertical-align: middle;
    }

    .wrapping {
        margin: 0 auto;
        margin-top: 30px;;
        padding: 20px;
        border-radius: 10px;
        font-size: 14px;
        color: black;
        width: 800px;
        background: transparent;
    }

    input.obfuscate, textarea, select, chzn-select, .chzn-container-single .chzn-single, .chzn-container-multi .chzn-choices, .blocky, input[type="checkbox"] {
        background: transparent;
        border: none;
        box-shadow: 0 0 0 inset;
        border-bottom: 1px solid #ffd61d;
        margin-top: 2px;
        font-size: 14px;
        color: black;
        text-align: center;
    }

    #searching-box {
        margin: 0 auto;
        text-align: center;
    }

    .chzn-container-multi .chzn-choices .search-choice {
        background: none;
        border: none;
        box-shadow: none;
        margin-top: 5px;
        color: black

    }

    select {
        width: auto;
    }


</style>
<script type="text/javascript">
    $(function () {

    })
</script>

<div class="top-block">
  <div class="row-fluid" style="margin-top: 60px;">
    <div class="span6" style="text-align: right">
      <%= image_tag "logo.png", :id => "site_logo" %>
    </div>
    <div class="span6">
      <h2>
        Renting done professionally
      </h2>
      <%= link_to "Login", "#", :class => "btn btn-inverse btn-large", :style => "color:white;" %>
      <%= link_to "Know More", "#", :class => "btn btn-warning btn-large", :style => "color:black;", :onclick => "$('#know-more').show();$('.top-block').animate({marginTop:'-=650'},1000)" %>
      <%= link_to "Free House Listing", "#", :class => "btn btn-large", :style => "color:black;" %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="wrapping">

      <%= form_for @searching do |s| %>
          <div id="searching-box" style="font-size: 20px;">
            <div style="text-align: left;margin-left: 110px;">
              Find me a &nbsp;
              <%= s.fields_for :searching_bhk_configs do |f| %>
                  <%= f.select :bhk_config_id, options_from_collection_for_select(@bhk_configs, 'id', 'name', 3), {}, {:multiple => true, :'data-placeholder' => " ", :style => "color:white;font-size:12px;width:200px;"} %>
              <% end %>
              at a budget
              of <%= s.select :budget, @budget_options, {:multiple => false}, {:style => "width:80px", :class => "obfuscate"} %>
              rupees
              <br>

              <div style="margin-top: 0px;">in and around&nbsp;
                <%= s.fields_for :searching_areas do |f| %>
                    <%= f.select :area_id, options_from_collection_for_select(@areas, 'id', 'name', [25, 27]), {}, {:multiple => true, :'data-placeholder' => " ", :class => "raised", :style => "width:470px;"} %>
                <% end %>
              </div>
              <br>
              <br>
              I would like the house to have the following features:
              <%= s.fields_for :searching_facilities do |f| %>
                  <%= f.select :facility_id, options_from_collection_for_select(@facilities, 'id', 'name', [11, 12]), {}, {:multiple => true, :'data-placeholder' => " ", :style => "width:550px;"} %>
              <% end %>
              <%= s.submit "Go", :class => "btn btn-large", :style => "font-size:20px;width:60px; margin-left:565px;margin-top:-70px;" %>
              <br>
              <br>
              <br>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<div id="know-more" style="margin-top: 260px; background: transparent;display: none;">
  <%= link_to "Back to Top", "#", :class => "btn btn-warning btn-large", :style => "color:black;", :onclick => "$('.top-block').animate({marginTop:'+=650'},1000, function(){$('#know-more').hide();})" %>
</div>

app/views/welcome/index.html.erb
<style type="text/css">
    body {
        background: black;
    }
    .menu-list img{
        width:80px;
    }

</style>
<div class="row-fluid" style="width:101%;margin-top: -5px;">
  <div class="span2" style="margin-left: -10px;font-size: 12px;">
    <div class="info-unit page-sized" style="background: black;border:none;">
      <!--<h2 style="color:white;">Cheers</h2>-->
      <!--<span style="font-weight: normal;font-size: 12px;color:white;">When the house is rocking, don't bother knocking...</span>-->
      <!--<br>-->
      <!--<br>-->

      <!--<div class="blocky"><%#= Flat.all.count %> Properties in database</div>-->
      <!--<div class="blocky"><%#= Flat.all.count %> Properties available</div>-->
      <!--<div class="blocky"><%#= Flat.all.count %> Properties available</div>-->
      <!--<div class="blocky"><%#= Flat.all.count %> Properties available</div>-->

      <div style="margin-left: 0px;margin-top: 10px">
        <ul style="list-style:none;" class="menu-list">
          <li><%= link_to image_tag("icons/building1.png"), add_building_path, :title => "New Building", :'data-content' => "<table><tr><td><img src='/assets/icons/building1.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to add new building.</td></tr></table>" %></li>
          <li><%= link_to image_tag("icons/flats1.png"), add_flat_path, :title => "New Flat", :'data-content' => "<table><tr><td><img src='/assets/icons/flats1.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to add information of new flat.</td></tr></table>" %></li>
          <li><%= link_to image_tag("icons/properties.png"), quick_property_index_path, :title => "Property Index", :'data-content' => "<table><tr><td><img src='/assets/icons/properties.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to go to the List of Properties.</td></tr></table>" %></li>
          <li><%= link_to image_tag("icons/new_property.png"), new_property_path, :title => "New Property", :'data-content' => "<table><tr><td><img src='/assets/icons/new_property.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to add a New Property.</td></tr></table>" %></li>
          <li><%= link_to image_tag("icons/contacts.png"), contacts_path, :title => "Contact List", :'data-content' => "<table><tr><td><img src='/assets/icons/contacts.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to go to the List of Contacts.</td></tr></table>" %></li>
          <li><%= link_to image_tag("icons/new_contact.png"), new_contact_path, :title => "New Contact", :'data-content' => "<table><tr><td><img src='/assets/icons/new_contact.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to add a New Contact.</td></tr></table>" %></li>

          <li style="color:white;font-size:18px;line-height:20px;">
            <% @interaction=Interaction.new %>
            <% @interaction.taskings.build %>

            <!--<a class="interaction-link" data-toggle="modal" href="#new_interaction_form" title="Add Interaction or Task" data-content="<table><tr><td><img src='/assets/icons/interaction.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to add an Interaction or Task.</td></tr></table>"><%= image_tag "icons/interaction.png" %></a>-->
          <li><%= link_to image_tag("icons/pois.png"), new_poi_path, :title => "Points Of Interest", :'data-content' => "<table><tr><td><img src='/assets/icons/pois.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to populate the map.</td></tr></table>" %></li>
          <li><%= link_to image_tag("icons/deals.png"), deals_path, :title => "Deals", :'data-content' => "<table><tr><td><img src='/assets/icons/deals.png' style='width:128px;vertical-align:middle;'/></td><td>Click here to capture and analyze deals.</td></tr></table>" %></li>

          <div class="modal hide fade" id="new_interaction_form" style="width:840px;height:500px;margin-left: -25%;overflow: hidden;">
            <div class="modal-header">
              <button class="close" data-dismiss="modal">×</button>
              <h1>Add Interaction</h1>
            </div>
            <div class="modal-body">
              <div class="row-fluid">
                <%#= render 'interactions/form', :locals => {} %>
              </div>
            </div>
          </div>
          </li>
          <!--<li style="color:white;font-size:18px;line-height:20px;background: #000000"><a href="#">Intranet</a></li>-->
        </ul>
        <%#= link_to "Property Search", "#", :class => "btn btn-inverse span2 sized" %>
        <%#= link_to "Contact Search", "#", :class => "btn span2 sized" %>
        <%#= link_to "Broker Search", "#", :class => "btn span2 sized" %>
        <%#= link_to "Recently Viewed", "#", :class => "btn span2 sized" %>
        <%#= link_to "Frequently Viewed", "#", :class => "btn span2 sized" %>
        <%#= link_to "Deals", "#", :class => "btn span2 sized" %>
        <%#= link_to "Data and Graphs", "#", :class => "btn span2 sized" %>
        <%#= link_to "Projects", "#", :class => "btn span2 sized" %>
        <%#= link_to "Settings", "#", :class => "btn span2 sized" %>
        <%#= link_to "Got Game?", "#", :class => "btn span2 sized" %>
        <%#= link_to "Intranet", "#", :class => "btn btn-inverse span2 sized" %>
      </div>
    </div>
  </div>

  <div class="span10" style="margin-left: -40px;">
    <div class="row-fluid">
      <!--Header and Search for Tasks-->
      <%= render 'layouts/partials/interaction_tasks_partial' %>
    </div>
  </div>
</div>