config/routes.rb
BPEv075::Application.routes.draw do

  resources :deals

  resources :deal_stages
  match 'flat/add',:to=>"flats#add", :as=>"add_flat"
  match 'res_data/:id',:to=>"searchings#res_data"

  match 'surveyor',:to=>"pois#surveyor", :as=>"surveyor"
  match 'building/new',:to=>"buildings#new", :as=>"add_building"
  match 'search_results/:id', :to=>"searchings#results", :as=>"search_result"
  match 'property/(:building_id)/quick_form', :to => "buildings#quick_form", :as => "new_property"
  match 'flat_table/', :to => "flats#quick_index", :as => "quick_property_index"
  match 'building/:building_id/flat/:id/detailed_form/basic', :to => "buildings#detailed_form", :as => "edit_property_basic"
  match 'building/:building_id/flat/:id/detailed_form/location', :to => "buildings#building_location", :as => "edit_property_location"
  match 'building/:building_id/flat/:id/detailed_form/building_features', :to => "buildings#building_features", :as => "edit_property_building_features"
  match 'building/:building_id/flat/:id/detailed_form/flat_features', :to => "buildings#flat_features", :as => "edit_property_flat_features"
  match 'building/:building_id/flat/:id/detailed_form/photos', :to => "buildings#photos", :as => "edit_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/tag_photos', :to => "buildings#tag_photos", :as => "tag_property_flat_photos"
  match 'building/:building_id/flat/:id/detailed_form/moreinfo', :to => "buildings#moreinfo", :as => "edit_property_flat_moreinfo"
  match 'building/:building_id/flat/:id/detailed_form/terms', :to => "buildings#terms", :as => "edit_property_terms"
  match 'building/:id/:flat_id', :to => "buildings#show", :as => "show_building"
  match 'property/:id', :to => "flats#show", :as => "show_property"
  match 'network_map/:id', :to => "contacts#network_map", :as => "network_map"
  match "building/crop", :to =>  "buildings#crop"

  match 'property/notes/:building_id/:flat_id', :to => "flats#notes", :as => "notes"
  match 'flatasks/:id', :to=> "flats#flatasks", :as => "flatask"

  resources :searchings
  resources :interaction_entities
  resources :taskings
  resources :interactions
  resources :interaction_types
  resources :contacts
  resources :connections
  resources :buildings
  resources :flats
  resources :tasks
  resources :photos
  resources :building_services
  resources :pois
  resources :flat_contacts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  devise_for :users
  match "reschedule" => "taskings#reschedule"
  match "get_contact_list" => "buildings#get_contact_list"
  match "markup_as_cancle/:id"=>"taskings#markup_as_cancle"
  match "markup_as_complete/:id"=>"taskings#markup_as_complete"
  match "rename_photo/:photo_id" => "photos#rename_photo", :as => "rename_photo"
  match "delete_all_photos/:flat_id" => "photos#delete_all_photos", :as => "delete_all_photos"
  match "make_showcase_image/:flat_id/:photo_id" => "photos#make_showcase_image", :as => "make_showcase_image"
  match "update_photo_sequence" => "photos#update_photo_sequence", :as => "update_photo_sequence"
  match "save_photo_positions/:photo_id/:xpos/:ypos" => "photos#save_photo_positions", :as => "save_photo_positions"
  match "make_floor_plan/:flat_id/:photo_id" => "photos#make_floor_plan", :as => "make_floor_plan"
  match "/create_floor_plan"  => "photos#create_floor_plan" , :as => "create_floor_plan"
  match "dashboard", :to => "welcome#index", :as => "dashboard"
  match "/crop_floorplan", :to => "buildings#crop_floorplan", :as => "crop_floorplan"

  root :to => 'welcome#home'

end

app/models/building.rb
class Building < ActiveRecord::Base
  geocoded_by :landmark   # can also be an IP address
  after_validation :geocode

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address

  has_many :flats, :dependent => :destroy
  has_many :building_localities
  has_many :localities, :through => :building_localities
  has_one :primary_locality
  has_and_belongs_to_many :moving_requirements
  has_and_belongs_to_many :restrictions
  has_many :building_notes, :dependent => :destroy
  has_many :building_routes, :dependent => :destroy
  has_many :building_services, :dependent => :destroy
  has_many :services, :through => :building_services

  has_many :building_facilities, :dependent => :destroy
  has_many :facilities, :through => :building_facilities
  has_many :building_facility_features, :dependent => :destroy
  has_many :facility_features, :through => :building_facility_features

  accepts_nested_attributes_for :flats, :reject_if => proc { |attrs| reject = %w(name bhk_config_id).all? { |a| attrs[a].blank? } }, :allow_destroy => true
  accepts_nested_attributes_for :building_notes, :reject_if => proc { |attrs| reject = %w(name).all? { |a| attrs[a].blank? } }, :allow_destroy => true
  accepts_nested_attributes_for :building_routes, :reject_if => proc { |attrs| reject = %w(name).all? { |a| attrs[a].blank? } }, :allow_destroy => true
  accepts_nested_attributes_for :building_services, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :building_localities, :reject_if => lambda { |a| a[:locality_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :primary_locality, :reject_if => lambda { |a| a[:locality_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :building_facilities, :reject_if => lambda { |a| a[:facility_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :building_facility_features, :reject_if => lambda { |a| a[:facility_feature_id].blank? }, :allow_destroy => true

  has_attached_file :avatar,
                    :styles => {
                        :original => {
                            :geometry => "640x600<",
                            #:watermark_path => "#{Rails.root}/app/assets/images/watermark.jpg",
                            :position => "Center"
                        },
                        :lightbox => {
                            :geometry => "640x600>"
                        },
                        :thumbnail => {
                            :geometry => "300x300!"
                        }
                    }

  after_save :make_poi

  def main_locality
    primary_locality_id.blank? ? nil :Locality.find(self.primary_locality_id)
  end

  def full_name
    main_locality.nil? ? "#{self.name}" : "#{self.name}, #{self.main_locality.name}"
  end

  def make_poi
    unless (self.latitude.blank? or self.longitude.blank?)
      if Poi.find_by_name(self.name).blank?
        @poi=Poi.new
        @poi.name=self.name
        @poi.locality_id=self.primary_locality_id
        @poi.poi_type_id=PoiType.find_by_name("Building").id
        @poi.note=self.qknote
        @poi.latitude=self.latitude
        @poi.longitude=self.longitude
        @poi.save
      end
    end
  end

  before_save :insert_qualities
  before_create :insert_qualities

  def insert_qualities
    if self.approach_quality_id.blank?
      self.approach_quality_id=2

    end
    if self.building_quality_id.blank?
      self.building_quality_id=2

    end

  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  autocomplete :building, :name

  before_filter :get_current_action

  def get_current_action
    @default_form_class="btn btn-inverse btn-large panel-link"
    case params[:action]
      when "detailed_form"
        @detailed_form_class="btn btn-primary btn-large panel-link"
      when "building_features"
        @building_form_class="btn btn-primary btn-large panel-link"
      when "flat_features"
        @flat_form_class="btn btn-primary btn-large panel-link"
      when "photos"
        @photos_form_class="btn btn-primary btn-large panel-link"
      when "building_location"
        @location_form_class="btn btn-primary btn-large panel-link"
      when "moreinfo"
        @moreinfo_form_class="btn btn-primary btn-large panel-link"
      when "terms"
        @terms_form_class="btn btn-primary btn-large panel-link"
      else
        @default_form_class="btn btn-inverse btn-large panel-link"

    end

  end

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json :@buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])
    @flat=Flat.find(params[:flat_id])
    @approach_quality=Quality.find(@building.approach_quality_id)
    @interiors_quality=Quality.find(@flat.interiors_quality_id)
    @view_quality=Quality.find(@flat.view_quality_id)
    @building_quality=Quality.find(@building.building_quality_id)
    @locality_quality=@building.main_locality.quality
    @overall_quality_value = ((@building_quality.value*2+@interiors_quality.value*2+@locality_quality.value*2+@approach_quality.value+@view_quality.value).to_f/8.0).round(0)
    @overall_quality_name = Quality.find_by_value(@overall_quality_value).name
    @flats=@building.flats
    @deals=Deal.all
    @building.building_notes.build
    @broker_relation=DealRelation.find_by_name("Broker")
    @landlord_relation=DealRelation.find_by_name("Landlord")
    @employee_relation=DealRelation.find_by_name("Employee")
    @tenant_relation=DealRelation.find_by_name("Tenant")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json :@building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.json
  def quick_form

    if params[:building_id].blank?
      @building = Building.new
      @building_selected = false
    else
      @building = Building.find(params[:building_id])
      @building_selected = true
    end


    @buildings = Building.all
    @localities = Locality.all
    @bhks=BhkConfig.all
    @sources=Flatype.all
    @furnstats=Furnstat.all
    @contacts=Contact.all
    @labellings=Labelling.where("is_flat_contact_label=?", true).all
    @rent_year= RentYear.where('name=?', Time.now.year).first

    @flat = @building.flats.build
    @expected_rent = @flat.expected_rents.build
    @available_from = @flat.available_froms.build

    if params[:contact]
      @default_contact_id=params[:contact]
    else
      @default_contact_id=0
    end

    @flat_contacts=@flat.flat_contacts.build
    @contact=@flat.contacts.build
    @phone=@contact.phones.build
    @email=@contact.emails.build
    @contact_types=ContactType.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json :@building }
    end
  end

  # GET /buildings/1/edit
  def detailed_form
    @building = Building.find(params[:building_id])
    @flat = Flat.find(params[:id])

    @buildings = Building.all
    @localities = Locality.all
    @bhks=BhkConfig.all
    @sources=Flatype.all
    @furnstats=Furnstat.all
    @contacts=Contact.all
    @labellings=Labelling.where("is_flat_contact_label=?", true).all
    @rent_year= RentYear.where('name=?', Time.now.year).first

    unless @expected_rent = @flat.expected_rents.first
      @expected_rent=@flat.expected_rents.build
    end
    unless @available_from = @flat.available_froms.first
      @available_from = @flat.available_froms.build
    end

    if params[:contact]
      @default_contact_id=params[:contact]
    else
      @default_contact_id=0
    end

    @flat_contacts=@flat.flat_contacts.build
    @contact=@flat.contacts.build
    @phone=@contact.phones.build
    @email=@contact.emails.build
    @contact_types=ContactType.all
    @building_selected=true
    #@available_from = @flat.available_froms.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json :@building }
    end
  end

  def building_location

    @building = Building.find(params[:building_id])
    @flat=Flat.find(params[:id])
    @localities=Locality.all
    @pois=Poi.where('poi_type_id=?', PoiType.find_by_name('Building').id).all
    @building.building_localities.build
    @building.building_routes.build unless !@building.building_routes.blank?

  end

  def building_features
    @building = Building.find(params[:building_id])
    @flat = Flat.find(params[:id])
    #@json = Building.all.to_gmaps4rails
    #@markers = Building.all.to_gmaps4rails    #@markers contain valid json to pass to the view

    @moving_requirements=MovingRequirement.all
    @qualities= Quality.all

    @facilities=Facility.where("is_building=?", true)
    @features=Hash.new
    @facilities.each do |facility|
      @features[facility.name]=facility.facility_features
    end

    @building.building_notes.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json :@building }
    end

  end

  def flat_features

    @flat = Flat.find(params[:id])
    @building = @flat.building

    @qualities = Quality.all
    @restrictions = Restriction.all
    @directions = Direction.all

    @flat_facilities = Facility.where("is_building=?", false)
    @flat_features = Hash.new
    @flat_facilities.each do |facility|
      @flat_features[facility.name] = facility.facility_features
    end

    @flat.flat_notes.build

    unless @flat_restrictions = @flat.flat_restrictions
      @flat_restrictions=@flat.flat_restrictions.build
    end

    @bathrooms=@flat.bathrooms
    @parkings=@flat.parkings
    @balconies=@flat.balconies

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json :@building }
    end

  end

  def photos
    @building = Building.find(params[:building_id])
    @flat = Flat.find(params[:id])
    @photos = Photo.all
    @photo = Photo.new

  end

  def crop_floorplan
    render :text => params
    return
    #@flat = Flat.find(params[:id])
    #@floorplan=@flat.floorplan
    #@flat.floorplan_file_name=@flat.photos.name
    #p @flat.floorplan_file_name


    # @floorplan.save


  end

  def moreinfo
    @building = Building.find(params[:building_id])
    @flat = Flat.find(params[:id])
    @services = Service.all
    @building_services=@building.building_services
    @building.building_services.build
    @building.building_services.each do |bs|
      bs.building_service_helplines.build
      bs.building_service_notes.build
    end


  end

  def terms
    @building = Building.find(params[:building_id])
    @flat = Flat.find(params[:id])

    if @flat.expected_rents.first.blank?
      @expected_rent=@flat.expected_rents.build
    else
      @expected_rent=@flat.expected_rents.first
    end

    if @flat.rental_terms.first.blank?
      @rental_term = @flat.rental_terms.build
    else
      @rental_term = @flat.rental_terms.first
    end

  end

  def tag_photos
    @building = Building.find(params[:building_id])
    @flat = Flat.find(params[:id])
    @photos = Photo.all
    @photo = Photo.new
    @floor_plan=@flat.photos.where("is_floor_plan=?", true).first
  end


  # POST /buildings
  # POST /buildings.json
  def create
    #render :text=>params
    #return
    @building = Building.new(params[:building])
    @contact=Contact.new(params[:contact])


    respond_to do |format|
      if !@contact.name.blank? && @contact.save!
        format.html { redirect_to new_property_path(:contact => params[:contact_id]), :notice => 'Contact was successfully created.' }
      elsif !params[:selected_building].blank?
        @selected_building=Building.find(params[:selected_building])
        format.html { redirect_to new_property_path(@selected_building, :contact => params[:contact_id]), :notice => "You selected #{@selected_building.name}. Now add the flat." }
      else
        if @building.save
          format.html { redirect_to new_property_path(@building, :contact => params[:contact_id]), :notice => 'Building was successfully created.' }
        else
          format.html { redirect_to new_property_path(@building, :contact => params[:contact_id]), :notice => "Property could not be created. You must choose a building and put in the flat name and configuration" }
        end
      end

    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update

    @building = Building.find(params[:id])

    @contact = Contact.new(params[:contact])
    respond_to do |format|

      if !@contact.name.blank?
        @contact.save!
      end

      if @building.update_attributes!(params[:building])

        case params[:came_from]
          when nil
            @flat=Flat.last
            @flat.flat_contacts.each do |flat_contact|
              flat_contact.contact.labellings<<flat_contact.labelling
            end
            format.html { redirect_to edit_property_basic_path(@building, @flat), :notice => 'Property was successfully created.' }
          when 'basic'
            @flat=Flat.find(params[:flat_id])
            @flat.flat_contacts.each do |flat_contact|
              flat_contact.contact.labellings<<flat_contact.labelling
            end
            format.html { redirect_to edit_property_location_path(@building, @flat), :notice => 'Basic Property data was successfully updated.' }
          when 'location'
            @flat=Flat.find(params[:flat_id])

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form_menu.html.erb
<div class="content" style="margin-top: 25px;">
  <div class="row-fluid">
    <div class="span5">
      <h1>
        <div class="blabel">Property</div>
        <small>Detailed Input Form</small>
      </h1>
      <h3>
        <div class="blabel">Building:</div>
        <small><%= @building.name %>, <%= @building.main_locality.name %></small>
        <br>

        <div class="blabel">
          Flat Key:
        </div>
        <small><%= link_to @flat.flat_key, flat_path(@flat) %></small>
      </h3>
    </div>
    <div class="span7 pull-right">
      <div class="row-fluid" style="margin-top: 20px;">
        <%= link_to "Basic Data", edit_property_basic_path(@building, @flat), :class => @detailed_form_class||=@default_form_class, :id => "basic" %>
        <%= link_to "Location", edit_property_location_path(@building, @flat), :class => @location_form_class||=@default_form_class, :id => "location" %>
        <%= link_to "Building", edit_property_building_features_path(@building, @flat), :class => @building_form_class||=@default_form_class, :id => "building" %>
        <%= link_to "Flat", edit_property_flat_features_path(@building, @flat), :class => @flat_form_class||=@default_form_class, :id => "flat" %>
        <%= link_to "Photos", edit_property_flat_photos_path(@building, @flat), :class => @photos_form_class||=@default_form_class, :id => "photos" %>
        <%= link_to "More Info", edit_property_flat_moreinfo_path, :class => @moreinfo_form_class||=@default_form_class, :id => "info" %>
        <%= link_to "Terms", edit_property_terms_path, :class => @terms_form_class||=@default_form_class, :id => "terms" %>
      </div>
    </div>
  </div>
</div>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Road</th>
    <th>Pincode</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buildings.each do |building| %>
  <tr>
    <td><%= building.name %></td>
    <td><%= building.address %></td>
    <td><%= building.road %></td>
    <td><%= building.pincode %></td>
    <td><%= building.latitude %></td>
    <td><%= building.longitude %></td>
    <td><%= link_to 'Show', building %></td>
    <td><%= link_to 'Edit', edit_building_path(building) %></td>
    <td><%= link_to 'Destroy', building, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Building', new_building_path %>

app/views/buildings/photos.html.erb
<%#=TODO: when the list is sorted the changes in sequence number should be reflected without making a page refresh  %>
<script type="text/javascript" src="/assets/jquery.Jcrop.js"></script>
<script type="text/javascript" src="/assets/jquery.color.js"></script>

<link rel="stylesheet" type="text/css" href="/assets/jquery.Jcrop.css">
<script type="text/javascript">
//    $(function() {
//        $('#target').Jcrop({
//            onChange: crop_picture,
//            onSelect: crop_picture,
//            setSelect: [0, 0, 500, 500],
//            aspectRatio: 1
//        });
//    });
//
//    function crop_picture(Coords,flat_id)
//    {
//
//        var rx = Coords.x;
//        //alert(rx);
//        var ry = Coords.y;
//        var rw = Coords.w;
//        var rh = Coords.h;
//        var data = {arx:[],ary:[],arw:[],arh:[],flat:[]};
//
//        data["arx"].push(rx);
//        data["ary"].push(ry);
//        data["arw"].push(rw);
//        data["arh"].push(rh);
//        data["flat"].push(<%#= @flat.id %>);
//
//
//        $.ajax({
//
//            type:'POST',
//            url:"/crop_floorplan",
//            data:JSON.stringify(data),
//            contentType: "application/json",
//            success:function (data){
//               // alert(data);
//            }
//            //dataType: dataType
//        });
//    }
//


    function rename_picture(this_photo) {
        var photo_id = this_photo;
        var photo_name = $('#photo_' + photo_id).val();
        var obj = {name:photo_name};

        $.ajax({

            type:'POST',
            url:"/rename_photo/" + photo_id,
            data:obj,
            success:function (data) {
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title:'Name Change Successful',
                    // (string | mandatory) the text inside the notification
                    text:'The Photo was renamed to ' + photo_name,
                    // (string | optional) the image to display on the left
                    image:'/assets/success.png',
                    // (bool | optional) if you want it to fade out on its own or just sit there
                    sticky:false,
                    // (int | optional) the time you want it to be alive for before fading out
                    time:'3000'
                    // (string | optional) the class name you want to apply to that specific message
                    // class_name:'my-sticky-class'
                });
            }
            //dataType: dataType
        });
    }


    function get_list_data(data) {

        var final_data = "";
        var intermediate_data = new Array();
        intermediate_data = data.split("&");
        for (var i = 0; i < intermediate_data.length; i++) {
            final_data = final_data + intermediate_data[i].split("=")[0].replace("[]", "=" + i) + "&"
        }
        final_data = final_data + "&flat_id=<%= @flat.id %>";
        return final_data;
    }


    $(function () {


        $("#sortable-photos").sortable({
            create:function (event, ui) {
                var final_data = get_list_data($("#sortable-photos").sortable("serialize"));
                $.ajax({

                    type:'POST',
                    url:"<%= update_photo_sequence_path %>",
                    data:final_data
                    //success: success,
                    //dataType: dataType
                });

            }

        }, {
            stop:function (event, ui) {
                delay: 300;

                var final_data = get_list_data($("#sortable-photos").sortable("serialize"));
                $.ajax({

                    type:'POST',
                    url:"<%= update_photo_sequence_path %>",
                    data:final_data
                    //                    success: function(){
                    //                    }
                    //dataType: dataType
                });


            }
        });


        $(".floor_plan").click(function () {
            var current_image = $(this);
            $.get("/make_floor_plan/" + "<%= @flat.id %>" + "/" + $(this).attr("id"), function (data) {
                current_image.parent().parent().css("background-color", "blue");
                $("#" + data).parent().parent().css("background-color", "black");
            })

        });


    });

</script>

<%= nested_form_for @building, :id => "kk", :html => {:multipart => true} do |b| %>
    <%= b.fields_for :flats, @flat, :html => {:multipart => true} do |f| %>

        <%= hidden_field_tag :came_from, "photos" %>
        <%= hidden_field_tag :flat_id, @flat.id %>
        <%= hidden_field_tag :external, false %>

        <%= f.hidden_field :name, :value => @flat.name %>
        <%= f.hidden_field :bhk_config_id, :value => @flat.bhk_config_id %>


        <%= render :partial => 'form_menu' %>
        <br>

        <div class="content detail-panel" id="basic-panel">

          <h2>Add Flat Photos
            <br>
            <small> You can choose multiple photos to upload
            </small>
          </h2>
          <%= file_field_tag 'flat[photos_attributes][][image]', :multiple => true %>
          <%= b.submit "Upload Photos", :class => "btn btn-inverse", :style => "margin-top:-8px;" %>
          <hr>


          <h2>Photo Gallery
            <%= link_to "Delete All", delete_all_photos_path(@flat.id), :class => "btn btn-danger", :confirm => "Are you sure ??" %>
            <%= link_to "Sequencify", edit_property_flat_photos_path(@building, @flat), :class => "btn btn-primary" %>
            <%= link_to "Taggify!", tag_property_flat_photos_path(@building, @flat), :class => "btn btn-inverse" %>
          </h2>
          <i>
            Drag and drop Photos in order to re-order sequence <br>
            Refresh (F5) to generate fresh sequence numbers or press Sequencify<br>
          </i>

          <div>
            <ul id="sortable-photos">
              <% @flat.photos.order("sequence_number").each_with_index do |photo, index| %>

                  <li id="<%= photo.id %>_<%= index %>">
                    <% @backcolor="black" %>
                    <% if photo.showcase_image? %>
                        <% @backcolor="green" %>

                    <% elsif photo.is_floor_plan? %>
                        <% @backcolor="blue" %>

                    <% end %>

                    <div class="image-wrapper" style="background-color: <%= @backcolor %>">
                      <span style="color: white;font-size: 18px;position:relative;top: -10px"><%= photo.sequence_number %></span>

                      <span style="color: white;font-size: 18px;position:relative;top: -10px"><%= link_to "x", photo, :method => :delete, :confirm => "Are you sure ??" %></span>
                      <br>
                      <%= link_to (image_tag(photo.image.url(:thumbnail), :size => "200x200", :id => photo.is_floor_plan? ? "target" :"")), make_showcase_image_path(@flat.id, photo.id) %>
                      <br>

                      <div>

                        <br>
                        <%= text_field_tag :caption, photo.name, :class => "input-large", :id => "photo_#{photo.id}" %>
                        <%= link_to "UPDATE", "#", :class => "btn btn-info pull-right", :onclick => "rename_picture('#{photo.id}')" %>
                        <br>
                        <% if photo.is_floor_plan==true %>

                            <%= link_to "Crop", "tag_photos", :class => "btn btn-info pull-right", :onclick => "crop_picture('#{photo.id}')" %>
                        <% end %>
                        <!--<%#= file_field_tag 'flat[photos_attributes][][image]' %>-->
                        <%#= link_to "Mark as Floor Plan", "#", :class => "btn btn-warning floor_plan", :id => photo.id %>
                        <br>

                      </div>
                    </div>
                  </li>

              <% end %>
            </ul>
          </div>
          <br>
          <br>
          <hr>
          <div class="row-fluid">
            <div class="span6">
              <% if @building.avatar.blank? %>
                  <h2>Add a Building Photo</h2>
                  <%= image_tag "missing_photo.jpg", :style => "border-radius:5px" %>
              <% else %>
                  <h2>Change the Building Photo</h2>
                  <br>
                  <%= image_tag @building.avatar.url(:thumbnail), :style => "border-radius:5px" %>
              <% end %>
              <br>
              <%= b.file_field :avatar %>
              <br>
              <%= b.submit "Upload Building Photo", :class => "btn btn-inverse", :style => "margin-top:-8px;" %>
              <br>

            </div>

            <div class="span6">
              <% if @flat.floorplan.blank? %>
                  <h2>Add Floor Plan
                    <br>
                    <small> Pick your floor plan
                    </small>
                  </h2>
                  <%= image_tag "missing_photo.jpg", :style => "border-radius:5px" %>
              <% else %>
                  <h2>Change the Floor Plan</h2>
                  <br>
                  <%= image_tag @flat.floorplan.url(:thumb),:id => "target", :style => "border-radius:5px" %>
              <% end %>
              <br>
              <%= f.file_field :floorplan  %>

              <br>
              <%= f.submit "Upload Floor Plan", :class => "btn btn-inverse", :style => "margin-top:-8px;" %>

                 <%= link_to "Crop", "tag_photos", :class=>"btn btn-danger fp_cropper", :style => "margin-top:-8px;", :onclick=> "crop_picture('#{@flat.id}')" %>

            </div>
          </div>
          <br>
          <br>
          <hr>
          <%= b.submit "Save and Continue", :class => "submitter btn btn-primary btn-large", :onclick => "$('#external').val('true')" %>
        </div>



    <% end %>
<% end %>